apiVersion: skaffold/v1beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: server-image
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: '*'
            dest: .
deploy:
  kubectl:
    manifests:
      - 'k8s/*'